/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Eleh Documentation",
  "description": "For someone that always ignore notif bar",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "About Me",
      "frontmatter": {},
      "regularPath": "/about/",
      "relativePath": "about/README.md",
      "key": "v-1b8f848a",
      "path": "/about/",
      "headers": [
        {
          "level": 2,
          "title": "Whats the reason i made this?",
          "slug": "whats-the-reason-i-made-this"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/images/logo.png",
        "heroText": "Eleh",
        "tagline": "The Weird Documentation Website",
        "actionText": "Letsgo →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "Novel",
            "details": "Weird hobby that makes you become a rare hooman."
          },
          {
            "title": "Chocolate",
            "details": "Chocolate can make your mood better, *but i prefer potato chips sstt."
          },
          {
            "title": "DND",
            "details": "This hooman mostly have a high-functional social filter, that means only some hooman can talk to her."
          }
        ],
        "footer": "Copyright © 2021 by Vi"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-9542cd4e",
      "path": "/"
    },
    {
      "title": "Cara Install",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-baaba128",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "Sebelum Install dan Sesudah Install",
          "slug": "sebelum-install-dan-sesudah-install"
        },
        {
          "level": 2,
          "title": "Issue Hot Reload",
          "slug": "issue-hot-reload"
        },
        {
          "level": 2,
          "title": "Perbandingan Vuepress dengan Readthedocs",
          "slug": "perbandingan-vuepress-dengan-readthedocs"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "About Me",
        "link": "/about/"
      }
    ],
    "sidebar": "auto"
  }
}